In [9]:
sudoku_facil = np.array([
    [4, 5, 6, 7, 0, 0, 3, 9, 8],
    [0, 0, 9, 0, 4, 8, 5, 0, 0],
    [8, 0, 0, 0, 0, 0, 0, 0, 1],

    [0, 4, 0, 1, 5, 0, 0, 0, 6],
    [0, 8, 0, 0, 0, 0, 0, 5, 0],
    [9, 0, 0, 0, 2, 7, 0, 3, 0],

    [5, 0, 0, 0, 0, 0, 0, 0, 3],
    [0, 0, 3, 4, 8, 0, 9, 0, 0],
    [2, 1, 4, 0, 0, 3, 7, 8, 5]
])


sudoku_medio = np.array([
    [2, 5, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 6, 0, 4, 0, 0, 0, 0],
    [0, 1, 4, 6, 0, 0, 5, 0, 0],

    [6, 0, 0, 0, 1, 0, 0, 0, 7],
    [0, 0, 2, 3, 0, 4, 9, 0, 0],
    [0, 0, 9, 0, 6, 0, 8, 0, 0],

    [0, 0, 7, 9, 0, 0, 6, 5, 0],
    [0, 0, 0, 0, 5, 0, 2, 0, 1],
    [0, 0, 0, 8, 0, 0, 0, 0, 3]
])


sudoku_dificil = np.array([
    [6, 0, 0, 0, 8, 0, 0, 0, 0],
    [0, 0, 9, 7, 0, 0, 0, 2, 8],
    [2, 0, 0, 0, 0, 0, 3, 0, 0],

    [0, 0, 0, 0, 0, 0, 0, 8, 0],
    [0, 0, 0, 4, 5, 0, 0, 9, 0],
    [0, 9, 3, 0, 2, 0, 0, 0, 1],

    [0, 0, 0, 6, 0, 0, 2, 0, 0],
    [4, 0, 6, 0, 0, 9, 0, 0, 0],
    [0, 0, 2, 3, 0, 0, 0, 0, 4]
])


In [ ]:
import time
import numpy as np

def encontrar_vazio(tabuleiro):
    for linha in range(9):
        for coluna in range(9):
            if tabuleiro[linha, coluna] == 0:
                return linha, coluna
    return None


def valor_valido(tabuleiro, linha, coluna, valor):
    # Linha
    if valor in tabuleiro[linha, :]:
        return False

    # Coluna
    if valor in tabuleiro[:, coluna]:
        return False

    # Bloco 3x3
    inicio_linha = (linha // 3) * 3
    inicio_coluna = (coluna // 3) * 3

    bloco = tabuleiro[
        inicio_linha:inicio_linha + 3,
        inicio_coluna:inicio_coluna + 3
    ]

    if valor in bloco:
        return False

    return True


def resolver_backtracking(tabuleiro):
    posicao = encontrar_vazio(tabuleiro)

    # Não existem mais células vazias
    if posicao is None:
        return True

    linha, coluna = posicao

    for valor in range(1, 10):

        if valor_valido(tabuleiro, linha, coluna, valor):

            tabuleiro[linha, coluna] = valor

            if resolver_backtracking(tabuleiro):
                return True

            # Retrocede
            tabuleiro[linha, coluna] = 0

    return False


def executar_backtracking(sudoku):
    tabuleiro = sudoku.copy()

    inicio = time.perf_counter()

    solucionado = resolver_backtracking(tabuleiro)

    fim = time.perf_counter()

    return {
        "solucao": tabuleiro,
        "solucionado": solucionado,
        "tempo": fim - inicio
    }

In [11]:
# ==========================================================
# EXECUÇÃO DO BACKTRACKING
# ==========================================================

instancias = {
    "Fácil": sudoku_facil,
    "Médio": sudoku_medio,
    "Difícil": sudoku_dificil
}

resultados_backtracking = {}


for dificuldade, sudoku in instancias.items():

    print("\n" + "=" * 60)
    print(f"BACKTRACKING - SUDOKU {dificuldade.upper()}")
    print("=" * 60)

    resultado = executar_backtracking(sudoku)

    resultados_backtracking[dificuldade] = resultado

    print(f"Solucionado: {resultado['solucionado']}")
    print(f"Tempo: {resultado['tempo']:.6f} s")
    print(f"Tempo: {resultado['tempo'] * 1000:.3f} ms")

    print("\nSolução:")
    print(resultado["solucao"])


# ==========================================================
# RESUMO FINAL
# ==========================================================

print("\n")
print("=" * 80)
print("RESUMO FINAL DO BACKTRACKING")
print("=" * 80)

for dificuldade, resultado in resultados_backtracking.items():

    print(f"\nSudoku {dificuldade}")
    print("-" * 50)

    print(f"Solucionado: {resultado['solucionado']}")
    print(f"Tempo: {resultado['tempo']:.6f} s")
    print(f"Tempo: {resultado['tempo'] * 1000:.3f} ms")


BACKTRACKING - SUDOKU FÁCIL
Solucionado: True
Tempo: 0.007519 s
Tempo: 7.519 ms

Solução:
[[4 5 6 7 1 2 3 9 8]
 [1 2 9 3 4 8 5 6 7]
 [8 3 7 5 9 6 4 2 1]
 [3 4 2 1 5 9 8 7 6]
 [7 8 1 6 3 4 2 5 9]
 [9 6 5 8 2 7 1 3 4]
 [5 9 8 2 7 1 6 4 3]
 [6 7 3 4 8 5 9 1 2]
 [2 1 4 9 6 3 7 8 5]]

BACKTRACKING - SUDOKU MÉDIO
Solucionado: True
Tempo: 3.588486 s
Tempo: 3588.486 ms

Solução:
[[2 5 8 1 9 3 4 7 6]
 [7 9 6 5 4 2 1 3 8]
 [3 1 4 6 7 8 5 2 9]
 [6 8 5 2 1 9 3 4 7]
 [1 7 2 3 8 4 9 6 5]
 [4 3 9 7 6 5 8 1 2]
 [8 2 7 9 3 1 6 5 4]
 [9 6 3 4 5 7 2 8 1]
 [5 4 1 8 2 6 7 9 3]]

BACKTRACKING - SUDOKU DIFÍCIL
Solucionado: True
Tempo: 15.881083 s
Tempo: 15881.083 ms

Solução:
[[6 3 5 1 8 2 9 4 7]
 [1 4 9 7 6 3 5 2 8]
 [2 8 7 5 9 4 3 1 6]
 [5 6 4 9 3 1 7 8 2]
 [8 2 1 4 5 7 6 9 3]
 [7 9 3 8 2 6 4 5 1]
 [3 1 8 6 4 5 2 7 9]
 [4 7 6 2 1 9 8 3 5]
 [9 5 2 3 7 8 1 6 4]]


RESUMO FINAL DO BACKTRACKING

Sudoku Fácil
--------------------------------------------------
Solucionado: True
Tempo: 0.007519 s
Tempo: 7.519 ms